version: '3.8'

services:

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  db:
    build:
      context: ./dev/db
    command: >
      -c ssl=off
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    ports:
      - "8432:8080"
    depends_on:
      - db

  uaa:
    build:
      context: ./dev/uaa
    ports:
      - "8080:8080"
    volumes:
      - ./dev/uaa/uaa.yml:/tmp/uaa/uaa/src/main/resources/uaa.yml:ro
