name: Deploy to cloud.gov prod space

on:
  push:
    branches:
      - main
    paths-ignore:
      - training-front-end/**
      
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
    secrets: inherit
