name: Continuous deployment to cloud.gov

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure secrets
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CG_USERNAME }}
          cf_password: ${{ secrets.CG_PASSWORD }}
          cf_org: gsa-smartpay
          cf_space: ${{ inputs.environment }}
          command: >-
            cf update-user-provided-service smartpay-training-secrets -p '{
              "JWT_SECRET": "${{ secrets.JWT_SECRET }}",
              "SMTP_PASSWORD": "${{ secrets.SMTP_PASSWORD }}"
            }'

      - name: Configure environment variables
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CG_USERNAME }}
          cf_password: ${{ secrets.CG_PASSWORD }}
          cf_org: gsa-smartpay
          cf_space: ${{ inputs.environment }}
          command: >-
            bin/cg-set-env.sh ${{ inputs.environment }}
            BASE_URL=${{ vars.BASE_URL }}
            SMTP_USER=${{ vars.SMTP_USER }}
            SMTP_SERVER=${{ vars.SMTP_SERVER }}
            SMTP_PORT=${{ vars.SMTP_PORT }}

      - name: Deploy the application
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CG_USERNAME }}
          cf_password: ${{ secrets.CG_PASSWORD }}
          cf_org: gsa-smartpay
          cf_space: ${{ inputs.environment }}
          cf_vars_file: manifest-vars.${{ inputs.environment }}.yml

      - name: Run database migrations
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CG_USERNAME }}
          cf_password: ${{ secrets.CG_PASSWORD }}
          cf_org: gsa-smartpay
          cf_space: ${{ inputs.environment }}
          command: cf run-task smartpay-training -c "alembic upgrade head"
