name: Frontend tests and code coverage

on:
  push:
    paths:
      - training-front-end/**
      - .github/**

jobs:
  unit-tests-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 
          
    permissions:
      contents: read
      pull-requests: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: training-front-end/package-lock.json

      - name: install dependencies
        run: npm ci

      - name: run linter
        run: npm run lint

      - name: code run coverage > 90 %
        run: npm run test:coverage -- --watch=false

      - name: Run pa11y 
        run: npm run pa11y-ci:gh 

      - name: Run broken link checker 
        run: npm run link-checker:pipeline 
